default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: template_app_development

test:
  <<: *default
  database: template_app_test

production:
  <<: *default
  database: template_app_production
  username: template_app
  password: <%= ENV['TEMPLATE_APP_DATABASE_PASSWORD'] %>
